# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e45999c8a8afe42d07e268f8c1c13770c79b529e68e43d6be73e4dcc5208f52d058cdb5a57e8db79fb4bb2100869cca49380fc2fd700f81a305f42290c025c9

test:
  secret_key_base: 3746de8aaf9211b402cb2e0aad050df0004a4c1764571e3f8ca33cb807ea28f77975cac742cdfb0580f58228b80945aadb3a4baeb1837449c06a6a1fa8227cdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
